title: unleash
description: Single-script MDM bypass for macOS — covers all 5 layers of Apple MDM enrollment
url: "https://unleash-nine.vercel.app"
baseurl: ""
theme: jekyll-theme-cayman
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: false
